// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example/hello.proto

#include "example/hello.pb.h"
#include "example/hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace example {

static const char* Hello_method_names[] = {
  "/example.Hello/SayHello",
};

std::unique_ptr< Hello::Stub> Hello::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Hello::Stub> stub(new Hello::Stub(channel));
  return stub;
}

Hello::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(Hello_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Hello::Stub::SayHello(::grpc::ClientContext* context, const ::example::HelloRequest& request, ::example::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::example::HelloRequest, ::example::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Hello::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::example::HelloRequest* request, ::example::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::example::HelloRequest, ::example::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Hello::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::example::HelloRequest* request, ::example::HelloReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::example::HelloReply>* Hello::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::example::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::example::HelloReply, ::example::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::example::HelloReply>* Hello::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::example::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

Hello::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Hello_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Hello::Service, ::example::HelloRequest, ::example::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Hello::Service* service,
             ::grpc::ServerContext* ctx,
             const ::example::HelloRequest* req,
             ::example::HelloReply* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
}

Hello::Service::~Service() {
}

::grpc::Status Hello::Service::SayHello(::grpc::ServerContext* context, const ::example::HelloRequest* request, ::example::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

